### ISSUE TITLE
invalid signature error

### ISSUE THREAD

**Issue by antonioandara** [DueDEX/API-Documentation#1]
I can't seem to get the signature right, I can check my position and other and my active orders but when  I try to send, delete or modify an order I always get an invalid signature error. I followed the signature example of the documentation and got the same example signature but whe I run the code with other parameters it won't work. This is the text I get from a regular order request

message = POST|/v1/order|1596027711419|||{"instrument":"BTCUSD","type":"limit","side":"long","price":8000,"size":10,"timeInForce":"ioc"}

**Comment by xJonathanLEI** [comment]
Sorry but we currently don't provide additional support for using API endpoints other than what's published on GitHub. You may checkout our official reference implementation [here](https://github.com/DueDEX/DueDex.NET). It's written in C# but you should still be able to find relevant signature code.
